sonar.projectKey=floriangiral_Bougnat_darts_counter
sonar.organization=floriangiral
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.exclusions=dist/**,coverage/**,test-results/**,node_modules/**,public/*.png,public/*.svg
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.qualitygate.wait=true
