export const STATS_LABELS_FR = {
  x01: {
    title: 'STATISTIQUES DU MATCH',
    tabs: {
      overview: "Vue d'ensemble",
      scoring: 'Scores',
    },
    columns: {
      metric: 'Mesure',
    },
    overview: {
      matchDuration: 'Duree du match',
      threeDartAverage: 'Moyenne 3 fleches',
      until170Average: 'Jusqu a 170',
      checkoutRate: 'Taux de checkout',
      highestCheckout: 'Meilleur checkout',
      highestScore: 'Meilleur score',
      averageWinningLegDarts: 'Moyenne manche gagnante (fleches)',
      averageWinningDarts: 'Moyenne fleches gagnantes',
      bestWorstLeg: 'Meilleure / Pire manche',
      winningDarts: 'Fleches gagnantes',
    },
    actions: {
      close: 'Fermer',
    },
  },
  statsView: {
    finished: 'MATCH TERMINE',
    winnerPrefix: 'Vainqueur:',
    unknownWinner: 'Inconnu',
    rematch: 'REVANCHE',
    exit: 'SORTIE',
  },
  cricket: {
    finished: 'CRICKET TERMINE',
    winnerPrefix: 'Vainqueur:',
    rematch: 'REVANCHE',
    exit: 'SORTIE',
    metricLabels: {
      mpr: 'Marks par tour (MPR)',
      totalMarks: 'Marks totaux',
      dartsThrown: 'Fleches lancees',
      pointAccuracy: 'Precision points',
    },
  },
  capital: {
    title: 'Statistiques Capital',
    emptyState: "Aucune statistique n'est disponible pour le moment.",
    backToMenu: 'Retour au menu',
    finalScore: 'Score Final',
    rankingPrefix: 'Classement #',
    successfulChallenges: 'Challenges reussis',
    successRate: 'Taux de reussite',
    pointsWon: 'Points gagnes',
    penalties: 'Penalites',
    bestRound: 'Meilleure manche',
    winningAverage: 'Moyenne gagnante',
    dartsThrown: 'Flechettes lancees',
    challengeDetails: 'Detail des challenges',
    dividedByTwo: 'DIVISE PAR 2',
    mainMenu: 'Menu Principal',
    replay: 'Rejouer',
    missedThrow: 'RATE',
  },
  triathlon: {
    modalTitle: 'Statistiques Triathlon',
    finished: 'Triathlon Termine',
    finalScoreDescription: 'Score final sur 100, construit avec les points de resultat et les bonus de performance.',
    finalTieBreakInfo: 'Egalite finale : vainqueur departage par un 501 supplementaire, commence par le gagnant du tir a la bulle initial.',
    competitor: 'Competiteur',
    total: 'Total',
    mainMenu: 'Menu Principal',
    rematch: 'Revanche',
    tieBreak: 'Departage',
  },
} as const;
