import type { DartMultiplier } from './dartsSpeechTypes';

export const NUMBER_WORDS: Record<string, number> = {
  zero: 0,
  un: 1,
  une: 1,
  one: 1,
  deux: 2,
  two: 2,
  trois: 3,
  three: 3,
  quatre: 4,
  four: 4,
  cinq: 5,
  five: 5,
  six: 6,
  sept: 7,
  seven: 7,
  huit: 8,
  eight: 8,
  neuf: 9,
  nine: 9,
  dix: 10,
  ten: 10,
  onze: 11,
  eleven: 11,
  douze: 12,
  twelve: 12,
  treize: 13,
  thirteen: 13,
  quatorze: 14,
  fourteen: 14,
  quinze: 15,
  fifteen: 15,
  seize: 16,
  sixteen: 16,
  dixsept: 17,
  seventeen: 17,
  dixhuit: 18,
  eighteen: 18,
  dixneuf: 19,
  nineteen: 19,
  vingt: 20,
  twenty: 20,
  trente: 30,
  thirty: 30,
  quarante: 40,
  forty: 40,
  cinquante: 50,
  fifty: 50,
  soixante: 60,
  sixty: 60,
  soixantedix: 70,
  seventy: 70,
  quatrevingt: 80,
  quatrevingts: 80,
  eighty: 80,
  quatrevingtdix: 90,
  ninety: 90,
  cent: 100,
  hundred: 100,
};

export const MULTIPLIER_WORDS: Record<string, DartMultiplier> = {
  single: 'single',
  simple: 'single',
  double: 'double',
  triple: 'triple',
};

export const SCORE_HINT_WORDS = new Set([
  'score',
  'je',
  'fais',
  'marque',
  'mis',
  'fait',
  'ca',
  'donne',
  'points',
  'point',
]);

export const REMAINING_HINT_WORDS = new Set([
  'reste',
  'laisse',
  'suis',
  'a',
  'ajouer',
  'jouer',
]);

export const IGNORE_WORDS = new Set([
  'and',
  'et',
  'avec',
  'mon',
  'mes',
  'ma',
  'de',
  'des',
  'du',
  'le',
  'la',
  'les',
  'my',
  'is',
  'ce',
  'qui',
  ...SCORE_HINT_WORDS,
  ...REMAINING_HINT_WORDS,
]);

export const MISS_WORDS = new Set([
  'x',
  'iks',
  'miss',
  'missed',
  'rate',
  'raté',
  'ratée',
  'manque',
  'manqué',
  'manquee',
  'manquée',
  'acote',
  'blanc',
  'dehors',
]);

export const HALF_BULL_WORDS = new Set(['outerbull', 'outer', 'demibulle', 'demie', 'demi']);
export const BULL_WORDS = new Set(['bull', 'bullseye', 'centre', 'pleincentre', 'interieur']);
