blank_issues_enabled: false
contact_links:
  - name: Groupe test WhatsApp
    url: https://chat.whatsapp.com/JCGYsdiNaYHAGAIjTOIaKg?mode=gi_t
    about: Pour un retour rapide, une capture ou une question simple, tu peux aussi passer par le groupe WhatsApp.
